#!/bin/bash
#curl cake-sdemo.rhcloud.com/roles/autoadd
#curl cake-sdemo.rhcloud.com/roles/auto_send_mails
curl http://venturenery-samyama.rhcloud.com/companies/get_companies_from_crunchbase
curl http://venturenery-samyama.rhcloud.com/companies/fetch_company_data